import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.argv[2]||'playwright');
const out=resolve('.test-artifacts');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1560,height:1100},deviceScaleFactor:1});
const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4174')&&!r.url().startsWith('data:'))external.push(r.url());});
await page.goto('http://127.0.0.1:4174',{waitUntil:'networkidle'});
await page.locator('#scene canvas').waitFor();
await page.locator('#tuning-button').click();
await page.selectOption('#visual-preset','clear');
assert.equal(await page.locator('#tune-exposure').inputValue(),'1.65');
await page.locator('#tune-exposure').fill('1.8');
assert.equal(await page.locator('#out-exposure').innerText(),'1.8');
await page.locator('#tune-labels').uncheck();
await page.waitForTimeout(100);
assert.equal(await page.locator('.asset-label:visible').count(),0);
await page.reload({waitUntil:'networkidle'});
await page.locator('#tuning-button').click();
assert.equal(await page.locator('#tune-exposure').inputValue(),'1.8');
assert.equal(await page.locator('#tune-labels').isChecked(),false);
await page.selectOption('#visual-preset','performance');
assert.equal(await page.locator('#tune-shadows').isChecked(),false);
await page.locator('#reset-tuning').click();
assert.equal(await page.locator('#tune-shadows').isChecked(),true);
const downloadPromise=page.waitForEvent('download');await page.locator('#export-tuning').click();
const download=await downloadPromise;await download.saveAs(resolve(out,'exported-look.json'));
await page.locator('#tuning-file').setInputFiles({name:'custom.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({exposure:1.6,labels:true,shadows:true,details:true}))});
await page.waitForFunction(()=>document.getElementById('tune-exposure').value==='1.6');
assert.equal(await page.locator('#tune-exposure').inputValue(),'1.6');
await page.locator('#reset-tuning').click();await page.locator('#close-tuning').click();
await page.waitForTimeout(1000);
await page.screenshot({path:resolve(out,'desktop-overview.png'),fullPage:true});
assert.equal(await page.locator('#scene canvas').count(),1);
assert.equal(await page.locator('.fallback').count(),0);
await page.locator('#play').click();await page.waitForTimeout(700);
assert(Number(await page.locator('#scrubber').inputValue())>0);
await page.locator('#play').click();const paused=await page.locator('#scrubber').inputValue();await page.waitForTimeout(200);assert.equal(await page.locator('#scrubber').inputValue(),paused);
await page.locator('#next').click();assert.match(await page.locator('.event-title').innerText(),/shared message board/);
await page.selectOption('#asset-select','a2');assert.match(await page.locator('#asset-detail').innerText(),/EXPLORING/);
await page.selectOption('#asset-select','a3');assert.match(await page.locator('#asset-detail').innerText(),/NORMAL/);
await page.locator('#previous').click();assert.match(await page.locator('.event-title').innerText(),/Evaluation/);
await page.locator('#scrubber').fill('132');assert.match(await page.locator('.event-title').innerText(),/Cluster access/);
await page.waitForTimeout(1300);await page.screenshot({path:resolve(out,'cluster-event.png'),fullPage:true});
assert.equal(await page.locator('#affected-systems').innerText(),'6');
await page.locator('#scrubber').fill('0');assert.equal(await page.locator('#affected-systems').innerText(),'0');
await page.locator('#agent').click();assert.equal(await page.locator('#stream-title').innerText(),'AGENT ACTIVITY');
await page.locator('#defender').click();
for(const mode of ['topology','attack','soc','timeline','kubernetes','identity','communication','infrastructure']){
  await page.selectOption('#view',mode);await page.waitForTimeout(75);assert.equal(await page.locator('#view').inputValue(),mode);
}
await page.locator('#scrubber').fill('132');await page.selectOption('#view','kubernetes');
assert.equal(await page.locator('.drilldown-card').count(),4);
assert.equal(await page.locator('.drilldown-card.is-affected').count(),4);
await page.locator('[data-inspect="worker"]').click();assert.equal(await page.locator('#asset-select').inputValue(),'worker');
await page.locator('#scrubber').fill('0');assert.equal(await page.locator('.drilldown-card.is-affected').count(),0);
await page.selectOption('#view','identity');assert.equal(await page.locator('.drilldown-card').count(),4);
await page.screenshot({path:resolve(out,'identity-drilldown.png'),fullPage:true});
await page.selectOption('#view','infrastructure');assert.equal(await page.locator('#drilldown').isVisible(),false);
await page.locator('#scrubber').fill('132');await page.selectOption('#view','soc');await page.locator('.alert-row').first().click();assert.equal(await page.locator('#view').inputValue(),'infrastructure');assert.equal(await page.locator('#asset-select').inputValue(),'cluster');
await page.locator('#restart').click();await page.locator('#teach').check();await page.selectOption('#speed','10');await page.locator('#play').click();
await page.locator('#teach-dialog').waitFor({state:'visible'});assert.match(await page.locator('#play').innerText(),/Play/);
await page.locator('#answers button').first().click();assert.match(await page.locator('#answer-feedback').innerText(),/Correct/);
await page.locator('#continue-lesson').click();await page.locator('#play').click();await page.locator('#teach').uncheck();
await page.locator('#sources-button').click();assert.equal(await page.locator('.source-card').count(),4);await page.keyboard.press('Escape');assert.equal(await page.locator('#source-dialog').isVisible(),false);
await page.locator('#scrubber').fill('228');assert.equal(await page.locator('#active-agents').innerText(),'0');await page.locator('#play').click();assert(Number(await page.locator('#scrubber').inputValue())<12);await page.locator('#play').click();
await page.locator('#restart').click();await page.selectOption('#speed','1');
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:resolve(out,'mobile.png'),fullPage:true});
await page.locator('#next').click();assert.match(await page.locator('.event-title').innerText(),/shared message board/);
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
writeFileSync(resolve(out,'browser-results.json'),JSON.stringify({passed:true,checks:['WebGL render','live visual sliders','presets','saved settings after reload','label toggle','shadow toggle','reset','JSON export/import','play/pause','previous/next','seek forward/backward','dual perspective','eight views','alert focus','teaching question','sources dialog','restart at end','mobile fit','no page errors','no external requests'],errors,external},null,2));
console.log('Browser checks passed. Screenshots and results:',out);await browser.close();

