import {score,candidates,matrix,parseCSV,search,makeGrid,summary,maxSubarray} from './core.mjs';
const $=id=>document.getElementById(id), page=document.body.dataset.project;
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const status=(text,error=false)=>{$('status').textContent=text;$('status').className='status'+(error?' error':'');};
const guard=fn=>async()=>{try{await fn();}catch(e){status(e.message,true);}};
const money=n=>n===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
if(page==='wordle'){
  const sample='apple ample angle ankle alone arena arise audio basic beach bench berry black blade blame blank bloom board brain bread break brick bring broad brown brush chair charm chase cheap check chess chief child claim class clean clear climb clock close cloud coach coast coral count crane cream crime cross crowd crown dance dealt death depth diary dirty doubt draft drain dream dress drink drive earth eight empty enjoy enter equal error event every exact exist extra faith false fancy fault field fight final first flame flash fleet floor flour focus force forth forty found frame fresh front fruit ghost giant given glass globe grace grade grain grand grape grass great green greet group guard guess guest guide habit happy heart heavy hello hence hobby honey horse hotel house human ideal image index inner input issue ivory jelly joint judge juice knife known label large laser later laugh layer learn least leave legal lemon level light limit liver local logic loose lover lower lucky lunch magic major maker mango maple march match mayor medal media metal meter might minor model money month moral motor mount mouse mouth movie music never night noise north novel nurse ocean offer often onion opera orbit order other outer owner paint panel paper party patch pause peace peach pearl penny phase phone photo piano piece pilot pitch place plain plane plant plate point polar pound power press price pride prime print prize proof proud queen quick quiet quite radio raise range rapid ratio reach ready reply right rival river robot rough round route royal rural scale scene score sense serve seven shade shake shall shape share sharp sheep sheet shelf shell shift shine shirt shock shore short shout sight since skill sleep slice slide slope small smart smile smoke snake solar solid solve sorry sound south space spare speak speed spend spice split sport spray stack stage stair stake stand start state steam steel steep stick still stock stone stood store storm story strip stuck study style sugar suite super sweet table taste teach teeth theme there thick thief thing think third those three throw tight timer tired title today token total touch tough tower trace track trade train treat trend trial tried truck truly trust truth twice under union unity upper upset urban usage usual valid value video visit vital voice waste watch water weary wheel where which while white whole whose woman women world worry worse worst worth would write wrong wrote yacht young youth zebra'.split(' ');
  let words=[...new Set(sample)],clues=[];
  const render=()=>{const matches=candidates(words,clues);$('results').replaceChildren(...matches.slice(0,300).map(w=>node('span',w,'chip')));$('clues').textContent=clues.map(([g,p])=>g+' '+p).join('\n');status(`${matches.length} matching words from ${words.length} loaded. ${matches.length>300?'Showing the first 300.':''}`);};
  $('guess-form').addEventListener('submit',e=>{e.preventDefault();const g=$('guess').value.trim().toLowerCase(),p=$('pattern').value.trim();if(!/^[a-z]{5}$/.test(g)||!/^[012]{5}$/.test(p)){status('Enter five letters and exactly five digits (0, 1, or 2).',true);return;}clues.push([g,p]);render();});
  $('undo').onclick=()=>{clues.pop();render();};$('reset').onclick=()=>{clues=[];render();};
  $('dictionary').onchange=guard(async()=>{const f=$('dictionary').files[0];if(!f)return;if(f.size>2_000_000)throw Error('Choose a word list smaller than 2 MB.');const entries=(await f.text()).trim().toLowerCase().split(/\s+/);if(entries.some(w=>!/^[a-z]{5}$/.test(w)))throw Error('Your list must contain only five-letter words separated by whitespace.');words=[...new Set(entries)];clues=[];render();});render();
}
if(page==='heatmap'){
  const sample='Team,Monday,Tuesday,Wednesday,Thursday,Friday\nAlpha,4,7,3,9,6\nBeta,8,2,5,7,4\nGamma,1,6,8,3,9\nDelta,5,4,7,6,2';
  $('csv').value=sample;
  const render=()=>{const m=matrix($('csv').value),flat=m.values.flat(),min=Math.min(...flat),max=Math.max(...flat);const colors={green:[33,111,77],blue:[40,90,160],purple:[105,61,151]};const color=colors[$('palette').value];const table=node('table',undefined,'heat');table.append(node('caption',`Heatmap · values from ${min} to ${max}; darker cells indicate larger values`));const head=node('tr');head.append(node('th','Row'));m.columns.forEach(c=>head.append(node('th',c)));const thead=node('thead');thead.append(head);table.append(thead);const body=node('tbody');m.values.forEach((row,i)=>{const tr=node('tr');const th=node('th',m.labels[i]);th.scope='row';tr.append(th);row.forEach(v=>{const t=max===min?.5:(v-min)/(max-min),rgb=color.map(c=>Math.round(250+(c-250)*t));const td=node('td',String(v));td.style.backgroundColor=`rgb(${rgb.join(',')})`;td.style.color=t>.58?'white':'#172927';tr.append(td);});body.append(tr);});table.append(body);$('heatmap').replaceChildren(table);status(`${m.values.length} rows × ${m.columns.length} columns. Data stays in your browser.`);};
  $('draw').onclick=guard(render);$('palette').onchange=guard(render);$('sample').onclick=()=>{$('csv').value=sample;render();};$('upload').onchange=guard(async()=>{const f=$('upload').files[0];if(!f)return;if(f.size>1_000_000)throw Error('Choose a CSV smaller than 1 MB.');$('csv').value=await f.text();render();});render();
}
if(page==='pathfinding'){
  let grid=makeGrid(42),run=0;
  const draw=(id,result,limit=Infinity,showPath=true)=>{const board=$(id);board.style.gridTemplateColumns=`repeat(${grid[0].length},1fr)`;const visited=new Set(result?.visited.slice(0,limit)),path=new Set(showPath?result?.path:[]);board.replaceChildren(...grid.flat().map((v,i)=>{const b=node('button',i===0?'S':i===grid.flat().length-1?'G':v===0?'■':String(v),'cell'+(v===0?' wall':path.has(i)?' path':visited.has(i)?' explored':''));if(i===0||i===grid.flat().length-1)b.className='cell endpoint';b.title=`Row ${Math.floor(i/grid[0].length)+1}, column ${i%grid[0].length+1}, ${v?'cost '+v:'wall'}`;b.setAttribute('aria-label',b.title+'. Toggle wall');b.onclick=()=>{if(i===0||i===grid.flat().length-1)return;run++;const r=Math.floor(i/grid[0].length),c=i%grid[0].length;grid[r][c]=grid[r][c]?0:1;redraw();status('Grid edited. Run the comparison again.');};return b;}));};
  const redraw=()=>{draw('dijkstra');draw('astar');$('d-metrics').textContent='Ready';$('a-metrics').textContent='Ready';};
  $('new-grid').onclick=()=>{const seed=Number($('seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){status('Use an integer seed from 0 to 4294967295.',true);return;}run++;grid=makeGrid(seed);redraw();status('Both algorithms use the same weighted grid.');};
  $('compare').onclick=async()=>{const token=++run,d=search(grid),a=search(grid,true);const animate=$('animate').checked&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
    if(animate)for(let n=1;n<=Math.max(d.visited.length,a.visited.length);n+=6){if(token!==run)return;draw('dijkstra',d,n,false);draw('astar',a,n,false);await new Promise(r=>setTimeout(r,35));}
    if(token!==run)return;draw('dijkstra',d);draw('astar',a);for(const [id,res] of [['d-metrics',d],['a-metrics',a]])$(id).textContent=`${res.cost===null?'No path':'Cost '+res.cost+' · '+res.path.length+' path cells'} · ${res.visited.length} explored`;
    status(d.cost===null?'No route reaches G. Click wall cells to open a route.':`Both algorithms found minimum cost ${d.cost}. A* uses Manhattan distance to guide its search.`);
  };redraw();
}
if(page==='housing'){
  let records=[],filtered=[],offset=0;const size=20;
  const renderTable=()=>{const body=$('rows');body.replaceChildren(...filtered.slice(offset,offset+size).map(r=>{const tr=node('tr');['Id','Neighborhood','HouseStyle','YearBuilt','GarageType','SalePrice'].forEach(k=>tr.append(node('td',k==='SalePrice'?money(r[k]):String(r[k]))));return tr;}));$('pagination').textContent=filtered.length?`${offset+1}–${Math.min(offset+size,filtered.length)} of ${filtered.length}`:'No matching homes';$('prev').disabled=offset===0;$('next').disabled=offset+size>=filtered.length;};
  const render=()=>{const lo=Number($('from').value),hi=Number($('to').value);if(!Number.isInteger(lo)||!Number.isInteger(hi)||lo>hi){status('Enter valid years with the start before the end.',true);return;}
    filtered=records.filter(r=>(!$('neighborhood').value||r.Neighborhood===$('neighborhood').value)&&(!$('style').value||r.HouseStyle===$('style').value)&&(!$('garage').value||r.GarageType===$('garage').value)&&r.YearBuilt>=lo&&r.YearBuilt<=hi);offset=0;const s=summary(filtered.map(r=>r.SalePrice));$('stats').replaceChildren(...[['Homes',s.count],['Mean',money(s.mean)],['Median',money(s.median)],['Minimum',money(s.min)],['Maximum',money(s.max)]].map(([k,v])=>{const d=node('div',k,'stat');d.append(node('strong',String(v)));return d;}));
    const groups=new Map();filtered.forEach(r=>{if(!groups.has(r.Neighborhood))groups.set(r.Neighborhood,[]);groups.get(r.Neighborhood).push(r.SalePrice);});const means=[...groups].map(([k,a])=>[k,summary(a).mean]).sort((a,b)=>b[1]-a[1]).slice(0,10),max=means[0]?.[1]||1;$('bars').replaceChildren(...means.map(([k,v])=>{const d=node('div');d.append(node('span',k));const track=node('div');const bar=node('div',undefined,'bar');bar.style.width=(100*v/max)+'%';track.append(bar);d.append(track,node('span',money(v)));return d;}));renderTable();status(`${filtered.length} of ${records.length} historical sales match your filters.`);
  };
  $('prev').onclick=()=>{offset=Math.max(0,offset-size);renderTable();};$('next').onclick=()=>{offset+=size;renderTable();};
  for(const id of ['neighborhood','style','garage','from','to'])$(id).onchange=render;
  $('reset').onclick=()=>{['neighborhood','style','garage'].forEach(id=>$(id).value='');$('from').value=1872;$('to').value=2010;render();};
  guard(async()=>{const response=await fetch('./ames-housing.csv');if(!response.ok)throw Error('The dataset could not load. Reload this page to retry.');const rows=parseCSV(await response.text()),headers=rows.shift();records=rows.map(row=>Object.fromEntries(headers.map((k,i)=>[k,['Id','YearBuilt','SalePrice'].includes(k)?Number(row[i]):row[i]])));for(const [id,key]of [['neighborhood','Neighborhood'],['style','HouseStyle'],['garage','GarageType']])for(const v of [...new Set(records.map(r=>r[key]))].sort())$(id).append(new Option(v,v));render();})();
}
if(page==='algorithms'){
  $('solve').onclick=guard(()=>{const parts=$('numbers').value.trim().split(/[\s,]+/),a=parts.map(Number);if(!parts[0]||a.length>1000||a.some(v=>!Number.isFinite(v)||Math.abs(v)>1e12))throw Error('Enter 1–1000 finite numbers between -1 trillion and 1 trillion.');const r=maxSubarray(a);$('answer').textContent=`Maximum sum: ${r.sum}\nPositions: ${r.start+1}–${r.end+1}\nSubarray: ${r.values.join(', ')}`;status('Calculated using a linear-time scan. Original divide-and-conquer coursework is included in the source folder.');});$('solve').click();
}
